general {
    border_size = 2
    gaps_in = 7
    gaps_out = 14
    col.active_border = rgb(8890d0)
    col.inactive_border = rgb(656a80)

    layout = dwindle
    no_focus_fallback = true
}

decoration {
    rounding = 8
    rounding_power = 4 

    shadow {
        enabled = true
        range = 6
        render_power = 4
        color = rgb(5e81ac)
        color_inactive = rgb(131926)
    }

    blur {
        passes = 2
            size = 7
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

animation = workspaces, 1, 5, default, slidevert

layerrule = blur, rofi
layerrule = blur, logout_dialog
layerrule = noanim, notifications$
