misc {
    vfr = true
    vrr = 1
    enable_anr_dialog = false
}

binds {
    workspace_center_on = 1
}

render {
    direct_scanout = 1
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

dwindle {
    preserve_split = true
}
