input {
    kb_layout = gb
    kb_variant = colemak
    kb_options = caps:capslock
    numlock_by_default = true
    repeat_rate = 30
    repeat_delay = 500
    accel_profile = flat
    follow_mouse = 1

    touchpad {
        # disable_while_typing = false
        natural_scroll = true
    }
}

gestures {
    gesture = 3, vertical, workspace
    workspace_swipe_use_r = true
}
